####
POST http://localhost:7777/product/create
Content-Type: application/json

{
    "collection": [
        {
            "name": "Boneka",
            "category": "Boneka Jak",
            "price": 4000
        },
        {
            "name": "Boneka",
            "category": "Boneka Jak",
            "price": 4000
        }
    ]
}
###
GET http://localhost:7777/product/read
###
GET http://localhost:7777/product/read?id=["",""]
###
DELETE http://localhost:7777/product/delete?id=["5ffd425f97fa7435609d5c15","5ffd4724c680fd36280be037"]

###
PUT http://localhost:7777/product/update?price=8000  
Content-Type: application/json
//tambahkan price di ujung url
{
    "collection": ["Boneka", "Boneka Jak" ]  //kategory yang ingin di update
}
####
PUT http://localhost:7777/product/update?name=Hoodie&category=Hoodie&price=5000&id=5ffd58f4a9baa130ccc4d789